//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteStudio.Modules.Toolbox.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebsiteStudio.Modules.Toolbox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function () {
        ///
        ///    var items = document.getElementsByClassName(&quot;accordion&quot;);
        ///
        ///    for (var i = 0; i &lt; items.length; i++) {
        ///        items[i].onclick = function () {
        ///            this.classList.toggle(&quot;active&quot;);
        ///        }
        ///    }
        ///
        ///})();.
        /// </summary>
        internal static string AccordionScript {
            get {
                return ResourceManager.GetString("AccordionScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .accordion {
        ///    @normal-color: #EEE;
        ///    @accent-color: #CCC;
        ///
        ///    background-color: @normal-color;
        ///    color: #444;
        ///    cursor: pointer;
        ///    padding: 15px;
        ///    width: 100%;
        ///    text-align: left;
        ///    border: none;
        ///    outline: none;
        ///    box-sizing: border-box;
        ///    font-weight: bold;
        ///
        ///    + div {
        ///        display: none;
        ///        padding: 20px;
        ///        border: 1px solid @accent-color;
        ///    }
        ///
        ///    &amp;.active, &amp;:hover {
        ///        background-color: @accent-color;
        ///    }
        ///
        ///    &amp;.active + div {
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccordionStyle {
            get {
                return ResourceManager.GetString("AccordionStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWTONSOFT JSON
        ///https://github.com/JamesNK/Newtonsoft.Json
        ///
        ///MIT-License
        ///Copyright (c) 2007 James Newton-King
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LicenseInfo {
            get {
                return ResourceManager.GetString("LicenseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function () {
        ///    function instance(container) {
        ///        var _Quotes = container.querySelectorAll(&apos;.quotes &gt; blockquote&apos;);
        ///        var _Progress = container.querySelector(&apos;.quotes &gt; .progress &gt; span&apos;);
        ///        var _Index = 0;
        ///        var _Interval = 10;
        ///
        ///        function hideAllExcept(except) {
        ///            for (var i = 0; i &lt; _Quotes.length; i++) {
        ///                if (i == except) {
        ///                    _Quotes[i].style.display = &apos;block&apos;;
        ///                }
        ///                else {
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuotesScript {
            get {
                return ResourceManager.GetString("QuotesScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .quotes {
        ///    position: relative;
        ///
        ///    blockquote &gt; .footer {
        ///        font-style: italic;
        ///
        ///        &amp;::before {
        ///            content: &apos;\2013  &apos;;
        ///        }
        ///    }
        ///
        ///    .progress {
        ///        margin: 20px;
        ///        height: 1px;
        ///        background-color: #EEE;
        ///        position: relative;
        ///
        ///        &gt; span {
        ///            background-color: #009;
        ///            position: absolute;
        ///            left: 0;
        ///            top: 0;
        ///            bottom: 0;
        ///
        ///            &amp;.run {
        ///                animation-name: quote [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuotesStyle {
            get {
                return ResourceManager.GetString("QuotesStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .timeline {
        ///    position: relative;
        ///    max-width: 800px;
        ///    padding-top: 4px;
        ///    padding-bottom: 4px;
        ///    margin: auto;
        ///    list-style: none;
        ///    margin: 10px;
        ///    padding-left: 35px;
        ///
        ///    &amp;::before {
        ///        content: &apos;&apos;;
        ///        position: absolute;
        ///        top: 0;
        ///        left: 18px;
        ///        height: 100%;
        ///        width: 4px;
        ///        background: #DDD;
        ///    }
        ///
        ///    &gt; li {
        ///        position: relative;
        ///        background-color: #F3F3F3;
        ///        padding: 0;
        ///        border: 1px solid #DDD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TimelineStyle {
            get {
                return ResourceManager.GetString("TimelineStyle", resourceCulture);
            }
        }
    }
}
