//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBuilder.Modules.Toolbox.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebsiteBuilder.Modules.Toolbox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function () {
        ///    function instance(container) {
        ///        var _Quotes = container.querySelectorAll(&apos;.quotes &gt; blockquote&apos;);
        ///        var _Progress = container.querySelector(&apos;.quotes &gt; .progress &gt; span&apos;);
        ///        var _Index = 0;
        ///        var _Interval = 10;
        ///
        ///        function hideAllExcept(except) {
        ///            for (var i = 0; i &lt; _Quotes.length; i++) {
        ///                if (i == except) {
        ///                    _Quotes[i].style.display = &apos;block&apos;;
        ///                }
        ///                else {
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuotesScript {
            get {
                return ResourceManager.GetString("QuotesScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .quotes {
        ///    position: relative;
        ///
        ///    blockquote &gt; .footer {
        ///        font-style: italic;
        ///
        ///        &amp;::before {
        ///            content: &apos;\2013  &apos;;
        ///        }
        ///    }
        ///
        ///    .progress {
        ///        margin: 20px;
        ///        height: 1px;
        ///        background-color: #EEE;
        ///        position: relative;
        ///
        ///        &gt; span {
        ///            background-color: #009;
        ///            position: absolute;
        ///            left: 0;
        ///            top: 0;
        ///            bottom: 0;
        ///
        ///            &amp;.run {
        ///                animation-name: quote [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuotesStyle {
            get {
                return ResourceManager.GetString("QuotesStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .timeline {
        ///    position: relative;
        ///    max-width: 800px;
        ///    padding-top: 4px;
        ///    padding-bottom: 4px;
        ///    margin: auto;
        ///
        ///    &amp;::before {
        ///        content: &apos;&apos;;
        ///        position: absolute;
        ///        top: 0;
        ///        left: 18px;
        ///        height: 100%;
        ///        width: 4px;
        ///        background: #DDD;
        ///    }
        ///
        ///    &gt; ul {
        ///        list-style: none;
        ///        margin: 10px;
        ///        padding-left: 35px;
        ///
        ///        &gt; li {
        ///            position: relative;
        ///            background-color: #F3F3F3;
        ///            p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TimelineStyle {
            get {
                return ResourceManager.GetString("TimelineStyle", resourceCulture);
            }
        }
    }
}
