//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteStudio.Modules.Gallery.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebsiteStudio.Modules.Gallery.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .gallery {
        ///	text-align:center;
        ///	margin:20px;
        ///
        ///    a {
        ///		opacity:0.8;
        ///        display: inline-block;
        ///        vertical-align:middle;
        ///		margin:10px;
        ///		padding:0;
        ///		cursor:zoom-in;
        ///
        ///        &amp;:hover {
        ///            opacity:1;
        ///        }
        ///
        ///		img {
        ///			border:0;
        ///			margin:0;
        ///			padding:0;
        ///			display:block;
        ///		}
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string GalleryStyles {
            get {
                return ResourceManager.GetString("GalleryStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAGNIFIC POPUP
        ///http://dimsemenov.com/plugins/magnific-popup
        ///
        ///The MIT License (MIT)
        ///
        ///Copyright (c) 2014-2016 Dmitry Semenov, http://dimsemenov.com
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of
        ///this software and associated documentation files (the &quot;Software&quot;), to deal in
        ///the Software without restriction, including without limitation the rights to
        ///use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
        ///the Software, and to permit persons to [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LicenseInfo {
            get {
                return ResourceManager.GetString("LicenseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Magnific Popup CSS */
        ///.mfp-bg {
        ///  top: 0;
        ///  left: 0;
        ///  width: 100%;
        ///  height: 100%;
        ///  z-index: 1042;
        ///  overflow: hidden;
        ///  position: fixed;
        ///  background: #0b0b0b;
        ///  opacity: 0.8; }
        ///
        ///.mfp-wrap {
        ///  top: 0;
        ///  left: 0;
        ///  width: 100%;
        ///  height: 100%;
        ///  z-index: 1043;
        ///  position: fixed;
        ///  outline: none !important;
        ///  -webkit-backface-visibility: hidden; }
        ///
        ///.mfp-container {
        ///  text-align: center;
        ///  position: absolute;
        ///  width: 100%;
        ///  height: 100%;
        ///  left: 0;
        ///  top: 0;
        ///  padding: 0 8px;
        ///  box-sizing: border-box;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MagnificCSS {
            get {
                return ResourceManager.GetString("MagnificCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! Magnific Popup - v1.1.0 - 2016-02-20
        ///* http://dimsemenov.com/plugins/magnific-popup/
        ///* Copyright (c) 2016 Dmitry Semenov; */
        ///!function(a){&quot;function&quot;==typeof define&amp;&amp;define.amd?define([&quot;jquery&quot;],a):a(&quot;object&quot;==typeof exports?require(&quot;jquery&quot;):window.jQuery||window.Zepto)}(function(a){var b,c,d,e,f,g,h=&quot;Close&quot;,i=&quot;BeforeClose&quot;,j=&quot;AfterClose&quot;,k=&quot;BeforeAppend&quot;,l=&quot;MarkupParse&quot;,m=&quot;Open&quot;,n=&quot;Change&quot;,o=&quot;mfp&quot;,p=&quot;.&quot;+o,q=&quot;mfp-ready&quot;,r=&quot;mfp-removing&quot;,s=&quot;mfp-prevent-close&quot;,t=function(){},u=!!window.jQuery,v=a(window), [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MagnificJS {
            get {
                return ResourceManager.GetString("MagnificJS", resourceCulture);
            }
        }
    }
}
